"""initial schema

Revision ID: 30c6d4d2067d
Revises: 
Create Date: 2026-09-10 12:58:12.708850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c6d4d2067d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graphs')),
    sa.UniqueConstraint('name', name=op.f('uq_graphs_name'))
    )
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('node_type', sa.Enum('central', 'category', 'data', name='node_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('fk_nodes_graph_id_graphs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('graph_id', 'node_id', name='uq_nodes_graph_id_node_id')
    )
    op.create_index('uq_nodes_one_central_per_graph', 'nodes', ['graph_id'], unique=True, postgresql_where=sa.text("node_type = 'central'"))
    op.create_table('data_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('fk_data_relations_graph_id_graphs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], name=op.f('fk_data_relations_source_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], name=op.f('fk_data_relations_target_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_relations')),
    sa.UniqueConstraint('graph_id', 'source_id', 'target_id', name='uq_data_relations_graph_source_target')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('fk_edges_graph_id_graphs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], name=op.f('fk_edges_source_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], name=op.f('fk_edges_target_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edges')),
    sa.UniqueConstraint('graph_id', 'source_id', 'target_id', name='uq_edges_graph_source_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('data_relations')
    op.drop_index('uq_nodes_one_central_per_graph', table_name='nodes', postgresql_where=sa.text("node_type = 'central'"))
    op.drop_table('nodes')
    op.drop_table('graphs')
    # ### end Alembic commands ###
